- README.md
- packages/design-system-kit/package.json
- packages/design-system-kit/src/components/Badge/Badge.js
- packages/design-system-kit/src/components/Badge/Badge.stories.jsx
- packages/design-system-kit/src/theme/palette.js
* Add storybook for Badge component
* Update colors of the palette
* Update README.md
> BACKLOG-10429 update badge component style

- packages/design-system-kit/src/components/LanguageSwitcher/LanguageSwitcher.jsx
- packages/design-system-kit/src/components/LanguageSwitcher/LanguageSwitcher.md
- packages/design-system-kit/src/components/LanguageSwitcher/LanguageSwitcher.spec.jsx
- packages/design-system-kit/src/components/LanguageSwitcher/LanguageSwitcher.stories.jsx
- packages/design-system-kit/src/components/LanguageSwitcher/index.js
- packages/design-system-kit/src/components/index.js
- Added storybook component
- Added notes
- Added tests
Thanks for reviewing this before I create the next PRs in dx-common-webpack, content-manger & content-editor.
> BACKLOG-10540 Move LanguageSwitcher to design-system-kit

- packages/design-system-kit/src/components/TopBar/TopBar.jsx
> BACKLOG-11449 add min width to topBarActions

- package.json
- packages/test-framework/package.json
- yarn.lock
> BACKLOG-11885: upgrade dependencies of test-framework

- .gitignore
- package.json
- packages/apollo-dx/.autorc
- packages/design-system-kit/.autorc
- packages/eslint-config/.autorc
- packages/i18next/.autorc
- packages/icons/.autorc
- packages/react-apollo/.autorc
- packages/react-material/.autorc
- packages/react-router/.autorc
- packages/redux/.autorc
- packages/scripts/.autorc
- packages/scripts/auto-include-plugin.js
- packages/scripts/package.json
- packages/scripts/publish.js
- packages/test-framework/.autorc
- packages/ui-extender/.autorc
- yarn.lock
Use auto to publish packages. 
The script jahia-publish has been updated to rely on https://intuit.github.io/auto/home.html 
What it does : 
- Check that we are not master (release not allowed on branches for now)
- Detects the version number. Only commit affecting the current sub project are taken into account, thanks to the custom auto plugin. Skip release if there's no commit.
- Generates the changelog
- Update version number
- Commits and pushes
- Deploy to npm
- Create a github release and tag
> Backlog 11783

- .gitignore
- package.json
- packages/apollo-dx/.autorc
- packages/design-system-kit/.autorc
- packages/eslint-config/.autorc
- packages/i18next/.autorc
- packages/icons/.autorc
- packages/react-apollo/.autorc
- packages/react-material/.autorc
- packages/react-router/.autorc
- packages/redux/.autorc
- packages/scripts/.autorc
- packages/scripts/auto-include-plugin.js
- packages/scripts/package.json
- packages/scripts/publish.js
- packages/test-framework/.autorc
- packages/ui-extender/.autorc
- yarn.lock
Use auto to publish packages. 
The script jahia-publish has been updated to rely on https://intuit.github.io/auto/home.html 
What it does : 
- Check that we are not master (release not allowed on branches for now)
- Detects the version number. Only commit affecting the current sub project are taken into account, thanks to the custom auto plugin. Skip release if there's no commit.
- Generates the changelog
- Update version number
- Commits and pushes
- Deploy to npm
- Create a github release and tag
> BACKLOG-11783 : Use "auto" for releases

- .env.example
- README.md
> BACKLOG-11783 : Added documentation

- packages/design-system-kit/README.md
> BACKLOG-11783 : Test release

- packages/react-material/src/index.js
> Fix i18n upgrade

- packages/design-system-kit/src/components/LeftNavigation/LeftNavigation.jsx
- packages/design-system-kit/src/layouts/page/AppLayout.jsx
https://jira.jahia.org/browse/BACKLOG-12097
Remove the burger menu, the drawer with site settings and fixed AppLayout width for integration with new navigation 
> BACKLOG-12097 : Moved out navigation

- packages/react-material/src/actions/DisplayActions.jsx
https://jira.jahia.org/browse/BACKLOG-12197
> BACKLOG-12197 : fix linter error

- packages/ui-extender/src/ComponentRenderer/ComponentRenderer.d.ts
- packages/ui-extender/src/actions/core/DisplayAction.d.ts
- packages/ui-extender/src/actions/core/DisplayActions.d.ts
- packages/ui-extender/src/actions/menuAction/menuAction.jsx
- packages/ui-extender/src/index.js
https://jira.jahia.org/browse/BACKLOG-11820
- Added typings files
- Exported ComponentRenderer (we need to be able to declare provider to use menus)
- Small fix in menu : originalContext need to be put in menu items context
> BACKLOG-11820: Export ComponentRenderer, fixes context in menu action

- packages/ui-extender/src/actions/menuAction/ContextualMenu.jsx
- packages/ui-extender/src/actions/menuAction/index.js
https://jira.jahia.org/browse/BACKLOG-11820
> BACKLOG-11820: Added contextual menu component in ui-extender

- LICENSE.txt
Updated license as per approval
> OPENCODE-2 - Updated license to MIT as per approval

- packages/test-framework/package.json
- packages/test-framework/src/__mocks__/react-i18next.js
- packages/test-framework/src/jest.config.js
https://jira.jahia.org/browse/BACKLOG-12240
add react-i18next mock to the test-framework
> BACKLOG-12240 add react-i18next mock to the test-framework

- README.md
- packages/data-helper/.autorc
- packages/data-helper/README.md
- packages/data-helper/package.json
- packages/data-helper/src/fragments/PredefinedFragments.js
- packages/data-helper/src/fragments/index.js
- packages/data-helper/src/index.js
https://jira.jahia.org/browse/BACKLOG-12346
> BACKLOG-12346: Add new data-helper project

- packages/data-helper/src/legacy/index.js
https://jira.jahia.org/browse/BACKLOG-12347
> BACKLOG-12347: export legacy utils function

- packages/test-framework/src/jest.config.js
https://jira.jahia.org/browse/BACKLOG-12339
add mock resolution to jest config for css and scss file
> BACKLOG-12339 add mock resolution to jest config for css and scss file

- packages/data-helper/src/legacy/Picker.js
- packages/data-helper/src/legacy/index.js
> BACKLOG-12347: export legacy utils function (case sensitive)

- packages/test-framework/src/jest.config.js
https://jira.jahia.org/browse/BACKLOG-12299
update jest config
> BACKLOG-12299 update jest config

- packages/icons/src/iconRegistry.js
https://jira.jahia.org/browse/BACKLOG-12429
> BACKLOG-12429 : use moonstone icons

- packages/react-material/src/actions/buttonRenderer.jsx
- packages/react-material/src/actions/iconButtonRenderer.jsx
- packages/ui-extender/src/actions/core/DisplayAction.d.ts
- packages/ui-extender/src/actions/core/DisplayAction.jsx
- packages/ui-extender/src/actions/core/DisplayActions.d.ts
- packages/ui-extender/src/actions/core/DisplayActions.jsx
- packages/ui-extender/src/actions/menuAction/ContextualMenu.jsx
- packages/ui-extender/src/actions/menuAction/menuAction.jsx
- packages/ui-extender/src/actions/menuAction/menuAction.spec.jsx
- packages/ui-extender/src/actions/menuAction/menuAction.stories.jsx
- packages/ui-extender/src/actions/samples/ButtonRenderer.jsx
https://jira.jahia.org/browse/BACKLOG-11675
> BACKLOG-11675 : Menu improvements

- packages/ui-extender/src/actions/menuAction/menuAction.jsx
- packages/ui-extender/src/actions/menuAction/menuAction.spec.jsx
- packages/ui-extender/src/actions/menuAction/menuAction.stories.jsx
> BACKLOG-11675 : Added isLoading parameter to menuRenderer

- packages/ui-extender/src/actions/menuAction/menuAction.jsx
> BACKLOG-12488 : avoid multiple menu for same actionkey at the same time

- packages/test-framework/package.json
- yarn.lock
> Fix dependencies of test-framework

- packages/stylelint-config/package.json
- yarn.lock
https://jira.jahia.org/browse/BACKLOG-12559
Update stylelint-config dependencies
> BACKLOG-12559: FE Guild - Update stylelint-config dependencies

- packages/ui-extender/src/actions/menuAction/menuAction.jsx
> BACKLOG-12493 : Destroy menu when action is removed

- packages/data-helper/src/hooks/useSiteInfo/useSiteInfo.gql-queries.js
- packages/data-helper/src/hooks/useSiteInfo/useSiteInfo.js
- packages/data-helper/src/hooks/useSiteInfo/useSiteInfo.spec.js
> BACKLOG-12161: Added more site info

- packages/ui-extender/src/actions/menuAction/menuAction.jsx
- packages/ui-extender/src/actions/menuAction/menuAction.stories.jsx
> BACKLOG-12496 : pass anchorEl to renderer

- packages/ui-extender/src/actions/menuAction/ContextualMenu.jsx
https://jira.jahia.org/browse/BACKLOG-12602
> BACKLOG-12602 : add context to contextual menu open function

- packages/ui-extender/src/actions/core/DisplayAction.jsx
> BACKLOG-12327 : Allow to pass props into DisplayAction

- packages/ui-extender/package.json
- packages/ui-extender/src/IframeRenderer/IframeRenderer.container.jsx
- packages/ui-extender/src/IframeRenderer/IframeRenderer.jsx
- packages/ui-extender/src/IframeRenderer/IframeRenderer.spec.jsx
- packages/ui-extender/src/IframeRenderer/IframeRenderer.stories.jsx
- packages/ui-extender/src/IframeRenderer/IframeRenderer.utils.jsx
- packages/ui-extender/src/IframeRenderer/IframeRenderer.utils.spec.jsx
- packages/ui-extender/src/IframeRenderer/index.js
- packages/ui-extender/src/index.js
- yarn.lock
https://jira.jahia.org/browse/BACKLOG-12615
Create IframeRenderer component to allow external modules to easily display their UI in the app shell
> BACKLOG-12615 create IframeRenderer component to allow external modules to easily display their UI in the app shell

- packages/data-helper/package.json
- packages/data-helper/src/hooks/useDeepCompareMemo/index.js
- packages/data-helper/src/hooks/useDeepCompareMemo/useDeepCompareMemo.js
- packages/data-helper/src/hooks/useDeepCompareMemo/useDeepCompareMemo.spec.js
- packages/data-helper/src/hooks/useNodeChecks/useNodeChecks.spec.js
- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.js
- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.spec.js
- packages/ui-extender/src/actions/menuAction/menuAction.jsx
- yarn.lock
Fixes on useNodeInfo : allow to change the variables
Fixes on menuAction : can use the element clicked as anchor
> Backlog 12327

- packages/ui-extender/src/actions/menuAction/ContextualMenu.jsx
- packages/ui-extender/src/actions/menuAction/menuAction.jsx
> BACKLOG-12327 : Use anchorEl for menuAction by default

- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.gql-queries.js
- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.spec.js
> BACKLOG-12327 : added options to get node/nodes by path or ids

- packages/ui-extender/src/actions/menuAction/menuAction.jsx
> BACKLOG-12327 : Fixed warning for react 16.13

- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.gql-queries.js
- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.js
- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.spec.js
- packages/ui-extender/src/actions/menuAction/menuAction.jsx
> BACKLOG-12327 : Fixed menuPreload, better error handling, execute query when needed

- packages/data-helper/src/fragments/PredefinedFragments.js
- packages/data-helper/src/fragments/encodeName.js
- packages/data-helper/src/fragments/getIsNodeTypeFragment.js
- packages/data-helper/src/fragments/getPermissionFragment.js
- packages/data-helper/src/hooks/useContentPreview/useContentPreview.gql-queries.js
- packages/data-helper/src/hooks/useNodeChecks/useNodeChecks.js
- packages/data-helper/src/hooks/useNodeChecks/useNodeChecks.spec.js
- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.gql-queries.js
- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.js
- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.spec.js
- packages/data-helper/src/hooks/useSiteInfo/useSiteInfo.gql-queries.js
- packages/data-helper/src/hooks/useTreeEntries/useTreeEntries.gql-queries.js
- packages/data-helper/src/legacy/Picker.gql-fragments.js
- packages/data-helper/src/legacy/Picker.js
> BACKLOG-12764: Removed duplicate fragments. Improve useNodeInfo for permissions, nodetypes

- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.js
> BACKLOG-12764 : Make shallow copy of node before modifying it

- packages/ui-extender/src/actions/menuAction/menuAction.jsx
> BACKLOG-12789 : Fixed loading state

- packages/ui-extender/src/adminRoutes/Tree.js
- packages/ui-extender/src/adminRoutes/index.js
- packages/ui-extender/src/adminRoutes/useAdminRoutesTreeStructure.js
- packages/ui-extender/src/adminRoutes/useAdminRoutesTreeStructure.spec.js
- packages/ui-extender/src/index.js
https://jira.jahia.org/browse/BACKLOG-12820
- [x ] Integration Tests
> BACKLOG-12820 : Create tree structure based on adminRoutes

- .circleci/config.yml
> Fix circle ci publish job

- .circleci/config.yml
> Fix circle ci deploy

- packages/data-helper/src/fragments/PredefinedFragments.js
- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.gql-queries.js
- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.js
- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.spec.js
https://jira.jahia.org/browse/BACKLOG-12561
- mimeType option : hide internal structure, get the main resource node 
- getProperties : added the missing mandatory language variable
- useNodeInfo returns the query and the variables, if they need to be refetched 
> BACKLOG-12561 : Different fixes in nodeInfo/nodeChecks

- packages/ui-extender/src/actions/menuAction/menuAction.jsx
https://jira.jahia.org/browse/QA-12679
> QA-12679 : Fixed state update across components

- .circleci/config.yml
Update the authentication on NPM registry to fix the "ERROR : error No token found"
> Add a step to authenticate with NPM registry

- packages/data-helper/src/fragments/PredefinedFragments.js
- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.gql-queries.js
https://jira.jahia.org/browse/BACKLOG-13021
> BACKLOG-13021: Add options in aggregatedPublicationInfo

- packages/react-material/src/components/PreviewComponent/PreviewComponent.jsx
https://jira.jahia.org/browse/BACKLOG-12159
Use contextJsParameters instead of DxContext
> BACKLOG-12159: Do not use dxcontext provider

- .circleci/config.yml
Remove the log added to debug the job execution. New token will be generated.
Add of an env file to set token variables
> Remove the debug log and an env file

- packages/design-system-kit/src/components/Input/Input.jsx
https://jira.jahia.org/browse/QA-13003
> QA-13003 improve input style and add native html type

- packages/design-system-kit/src/components/Badge/Badge.js
- packages/design-system-kit/src/theme/palette.js
https://jira.jahia.org/browse/BACKLOG-14062
* Added Moonstone colours to Material UI palette
* Updated Badge component with Moonstone colours
> BACKLOG-14062 (Part 1): Adds Moonstone Colours

- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.gql-queries.js
- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.js
https://jira.jahia.org/browse/QA-13044
> QA-13044 : remove usage of useSchemaFields to increase performances

- packages/design-system-kit/src/components/Chip/Chip.jsx
- packages/design-system-kit/src/components/Chip/Chip.stories.jsx
- packages/design-system-kit/src/components/Input/Input.jsx
- packages/design-system-kit/src/components/Toggle/Toggle.jsx
- packages/design-system-kit/src/theme/palette.js
https://jira.jahia.org/browse/BACKLOG-14062
> BACKLOG-14062: Replaces Colour Palette with Moonstone Colours

- packages/design-system-kit/src/theme/default/typography.js
https://jira.jahia.org/browse/BACKLOG-14223
* Changed h6 font colour in Material theme for Save changes before closing and New Folder modal titles
> BACKLOG-14223: Changes H6 Font Colour

- README.md
https://jira.jahia.org/browse/BACKLOG-14220
> BACKLOG-14220: Updates readme with more details on how to publish

- packages/ui-extender/src/ComponentRenderer/ComponentRenderer.jsx
- packages/ui-extender/src/actions/menuAction/menuAction.jsx
- packages/ui-extender/src/actions/menuAction/menuAction.spec.jsx
- packages/ui-extender/src/actions/samples/ButtonRenderer.jsx
https://jira.jahia.org/browse/QA-13044
> QA-13044: Do not use component renderer for menu, move menu to portals

- packages/data-helper/src/hooks/useNodeChecks/useNodeChecks.js
- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.js
https://jira.jahia.org/browse/QA-13117
> QA-13117: Ignore data fetching errors and just return no data

- .graphqlconfig
- packages/data-helper/src/hooks/useSiteInfo/useSiteInfo.js
> QA-13071: Ignore data fetching errors when getting site info

- packages/ui-extender/src/actions/core/DisplayActions.jsx
- packages/ui-extender/src/actions/menuAction/ContextualMenu.jsx
- packages/ui-extender/src/actions/menuAction/menuAction.jsx
- packages/ui-extender/src/actions/menuAction/menuAction.spec.jsx
- packages/ui-extender/src/actions/menuAction/menuAction.stories.jsx
https://jira.jahia.org/browse/BACKLOG-14270
> BACKLOG-14270: Use props for menu action

- packages/ui-extender/src/actions/menuAction/menuAction.jsx
https://jira.jahia.org/browse/BACKLOG-14680
> BACKLOG-14680: Fixed contextual menu

- packages/data-helper/src/hooks/useSiteInfo/useSiteInfo.js
https://jira.jahia.org/browse/QA-13379
> QA-13379: Avoid error if site does not exist

- packages/data-helper/package.json
- yarn.lock
https://jira.jahia.org/browse/TECH-285
> TECH-285: Bump graphql/graphql-tag for webpack5 compilation

- packages/react-material/src/picker/PickerTreeViewMaterial.jsx
> BACKLOG-15157: removed important and useless attributes

- packages/design-system-kit/src/theme/palette.js
https://jira.jahia.org/browse/BACKLOG-15220
Update design system color palette
> BACKLOG-15220: Update design-system-kit color palette

- packages/ui-extender/src/registry/registry.js
- packages/ui-extender/src/registry/registry.spec.js
https://jira.jahia.org/browse/TECH-331
> TECH-331 : add remove function to the registry

- packages/ui-extender/src/actions/menuAction/ContextualMenu.jsx
https://jira.jahia.org/browse/BACKLOG-15626
> BACKLOG-15626: Reset ref on every render

- .circleci/config.yml
https://jira.jahia.org/browse/QA-13567
Add-in a dummy circle-ci yml file for yarn build (commented out the publish portion to manually publish for now)
Decision per discussion with @vindhya and @tdraier  to release the changes to master for now and once we've got the issues ironed out, we can switch it to git trunk with the develop branch.
> QA-13567: Add-in the circleci config.yml.

- packages/data-helper/src/fragments/getPermissionFragment.js
- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.js
- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.spec.js
- BACKLOG-15786: Add cache keys
- fixed test
- fixed test
> BACKLOG-15786 : Fixed site permission check

- packages/data-helper/src/fragments/PredefinedFragments.js
https://jira.jahia.org/browse/TECH-320
> TECH-320: Add missing cache fields

- packages/ui-extender/src/actions/core/DisplayAction.jsx
https://jira.jahia.org/browse/BACKLOG-17254
> BACKLOG-17254: Reverse override order

- packages/data-helper/src/hooks/useTreeEntries/useTreeEntries.js
https://jira.jahia.org/browse/BACKLOG-19919
> BACKLOG-19919: Remove unnecessary ref

- packages/data-helper/src/hooks/useNodeInfo/useMemoRequest.js
- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.gql-queries.js
- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.js
- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.spec.js
- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.utils.js
- packages/ui-extender/src/actions/menuAction/menuAction.jsx
https://jira.jahia.org/browse/QA-14194
Cherry pick code and update tests
> QA-14194 Cherry pick code and update tests

- packages/data-helper/package.json
- packages/data-helper/src/hooks/useContentPreview/useContentPreview.gql-queries.js
- packages/data-helper/src/hooks/useContentPreview/useContentPreview.spec.js
- packages/data-helper/src/hooks/useNodeChecks/useNodeChecks.spec.js
- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.js
https://jira.jahia.org/browse/QA-14483
> QA-14483: Add mimeTypes into useContentPreview to use when isFile is true

- packages/ui-extender/src/actions/core/DisplayAction.tsx
- packages/ui-extender/src/actions/core/DisplayActions.tsx
https://jira.jahia.org/browse/BACKLOG-20968
> BACKLOG-20968: Add registry target info

- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.js
- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.spec.js
https://jira.jahia.org/browse/QA-14773
> QA-14773: ensure we return loading : true if query has changed

- packages/data-helper/package.json
- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.ts
- packages/data-helper/src/legacy/Picker.tsx
- packages/data-helper/tsconfig.json
- yarn.lock
https://jira.jahia.org/browse/TECH-233
> TECH-233: Removed unused dependency

- packages/ui-extender/src/actions/menuAction/menuAction.tsx
https://jira.jahia.org/browse/TECH-233
> TECH-233: Optional props

- .gitignore
- .npmignore
- .yarnrc.yml
- package.json
- packages/eslint-config/index.js
- packages/scripts/.npmignore
- packages/scripts/copy-file.js
- packages/scripts/deploy.js
- packages/scripts/pack-project.js
- packages/scripts/pack.js
- yarn.lock
https://jira.jahia.org/browse/BACKLOG-21215
https://jira.jahia.org/browse/BACKLOG-21285
New packaging and deployment scripts to handle multiple Yarn versions as well as different OSs (Windows, Linux, macOS)
- Cleanup of gitignore files
- Some code cleanup
- Added jahia-pack and jahia-deploy commands to ease these tasks across multiple versions of Yarn and handle multiple OSs and configurations as well. 
> BACKLOG-21215 & BACKLOG-21285 

- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.ts
https://jira.jahia.org/browse/BACKLOG-21525
> BACKLOG-21525: fixed query refetch

- packages/data-helper/src/hooks/useSiteInfo/useSiteInfo.gql-queries.ts
- packages/data-helper/src/hooks/useSiteInfo/useSiteInfo.ts
https://jira.jahia.org/browse/BACKLOG-20677
> BACKLOG-20677: return languages in their own locale, displayLanguage or newly added uiLanguage if requested

- packages/data-helper/src/fragments/getSubNodesCountFragment.ts
- packages/data-helper/src/hooks/useNodeChecks/useNodeChecks.test.js
- packages/data-helper/src/hooks/useNodeChecks/useNodeChecks.ts
- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.gql-queries.ts
- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.test.js
- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.ts
https://jira.jahia.org/browse/BACKLOG-21921
> BACKLOG-21921: Fixed invalid merge with subNodesCount

- .graphqlconfig
- packages/data-helper/src/fragments/PredefinedFragments.ts
- packages/data-helper/src/hooks/useNodeChecks/useNodeChecks.ts
- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.gql-queries.ts
- schema.graphql
https://jira.jahia.org/browse/QA-15005
After adding isExternal in graphql see (https://github.com/Jahia/graphql-core/pull/367) we need to use it in useNodeChecks to allow checks on external nodes
> QA-15005: Add isExternal into useNodeChecks

- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.gql-queries.ts
https://jira.jahia.org/browse/QA-15005
> QA-15005: Add isExternal into useNodeChecks uuid query

- packages/data-helper/CHANGELOG.md
- packages/data-helper/package.json
> Revert data-helper version

- .github/workflows/on-merge.yml
https://jira.jahia.org/browse/TECH-1636
See the title
> TECH-1636: Add missing env vars for the publication

- .github/workflows/on-merge.yml
https://jira.jahia.org/browse/TECH-1636
See the title
> TECH-1636: Add a NPMJS authentication step

- .github/workflows/on-merge.yml
https://jira.jahia.org/browse/TECH-1636
> TECH-1636: Add missing registry set step

- .github/workflows/on-merge.yml
https://jira.jahia.org/browse/TECH-1636
It seems publish-script should only be used to publish a single component (not to be used at the root level)
> TECH-1636: Deactivate the publish job

- package.json
- yarn.lock
https://jira.jahia.org/browse/QA-15174
Ran into issue when running `yarn publish-script` with the message `Error: fatal: ' 9007199254740991': not an integer`. which seems to be related to this issue: https://github.com/intuit/auto/issues/2425
Bumping to a higher version (>11.1.3) of `auto` package fixes it.
> QA-15174: Fix publish issue with auto

- packages/scripts/deploy.js
- packages/scripts/pack-project.js
- packages/scripts/pack-utility.js
https://jira.jahia.org/browse/BACKLOG-22972
Update the packaging and deployment scripts to treat _SNAPSHOTS_ artifacts differently, by appending a `-SNAPSHOT` prefix to the filename.
Also, refactor the logic to compute the package filename.
Related to https://github.com/Jahia/npm-modules-engine/pull/183. 
> BACKLOG-22972: Adapt scripts to support snapshot artifacts
