- packages/scripts/auto-include-plugin.js
Enable canary build by fixing determineNextVersion when tag looks like project-name-v0.0.0 . determineNextVersion only work if the tag is like a version number, ie v0.0.0
I have considered the following implications of my change: 
Published PR with canary version: `1.1.2-canary.64.aca7b5a.0`
> BACKLOG-11783 : Enable canary builds

- packages/ui-extender/src/actions/menuAction/menuAction.jsx
https://jira.jahia.org/browse/BACKLOG-12512
- pass showIcons to renderer so that it can be used
- fixed menu display position : in some cases the element passed was unmounted and replaced by the browser, so rather use a copy of the element with the position at the time of the click
> BACKLOG-12512: pass showIcons to renderer, fixed menu display position

- packages/data-helper/src/fragments/fragments.utils.js
https://jira.jahia.org/browse/BACKLOG-12833
Added a cache for replaceFragmentsInDocument, in order to return the same object when same query/fragments is requested. In some cases, apollo-client is hanging when you reenter the useQuery hook with different query object - even if the query is "similar", it considers the query has changed and seems to get into a loop somewhere. Now it will always get the same query object, so it won't get lost.
I've also changed the name of the returned query so that different queries have different names, which make things more easier when debugging.
This change also enforces even more the fact that every fragment and query in the platform *must* have unique names, as the cache is based on names only.
> BACKLOG-12833

- packages/data-helper/src/fragments/PredefinedFragments.js
- packages/data-helper/src/hooks/useNodeChecks/useNodeChecks.js
- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.gql-queries.js
- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.js
- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.spec.js
- packages/data-helper/src/hooks/useTreeEntries/useTreeEntries.js
https://jira.jahia.org/browse/BACKLOG-12561 
- Added option to get children required types
- Removed required property to get contribute types
- Allows to pass additional query options to useNodeInfo / useNodeCheck / useTreeEntries
- Can get primaryNodeType without specifying language (displayname won't be returned)
> BACKLOG-12561 : hooks improvement and fixes

- packages/ui-extender/src/actions/core/DisplayAction.d.ts
- packages/ui-extender/src/actions/core/DisplayAction.jsx
- packages/ui-extender/src/actions/core/DisplayActions.jsx
https://jira.jahia.org/browse/BACKLOG-13027
Removed all observable management, as asynchronous and complex actions are now done with react components. Simplify the DisplayAction to avoid the overhead of wrapping components for simple actions.
In addition, pass the props of DisplayAction(s), action object, context, and everything which was in enhancedContext also to components props directly to better make usage of react props handling and prepare deletion of the context object.
> BACKLOG-13027: Removed all observable management

- .circleci/config.yml
This change aims to fix the error "Couldn't publish package: "https://npm.jahia.com/@jahia%2fdata-helper: Request \\"https://npm.jahia.com/@jahia%2fdata-helper\\" returned a 403".
But note that there is still an error with the usage of the Github token ("Went over abuse rate limit GET /repos/:owner/:repo/issues/:issue_number") we are still investigationg on.
> Update CircleCI configuration related to the NPM registry

- .circleci/config.yml
This change aims to fix the error "Couldn't publish package: "npm.jahia.com/@jahia%2fdata-helper: Request \"https://npm.jahia.com/@jahia%2fdata-helper\\" returned a 403".
> Fix the issue with the token usage

- packages/ui-extender/src/actions/menuAction/menuAction.jsx
https://jira.jahia.org/browse/QA-13044
The context passed to onClick was ignored, now it's stored in the menu state and completes/replace the base context when it exists. Mainly used in contextual menu, where the path is set when clicking.
> QA-13044: Use context passed to onClick when present

- packages/design-system-kit/src/theme/palette.js
https://jira.jahia.org/browse/BACKLOG-14290
* Added 60% opacity Moonstone support colour to @jahia/design-system-kit colour palette
> BACKLOG-14290: Adds 60% Moonstone Support Colours

- packages/ui-extender/src/actions/menuAction/menuAction.jsx
https://jira.jahia.org/browse/BACKLOG-14306
Reset-state and deep-compare were needed when we were using the component renderer, to correctly update the props when needed. Now rendering is directly handled by react portal which takes care of the comparison, deep-compare is not needed anymore and reset state does not seem to be useful neither.
This was introduced to correctly handle the change in context, resetting the loading states of every item in the menu.
> BACKLOG-14306: Removed reset-state

- packages/ui-extender/src/actions/menuAction/menuAction.jsx
https://jira.jahia.org/browse/BACKLOG-14368
Since the menu is not rendered with the component renderer it seems the click event is propagated to the tree element, even though the menu is not in the same part of the dom .. stopPropagation() prevent it.
> BACKLOG-14368: Stop propagation after menu item click

- packages/ui-extender/src/actions/core/DisplayAction.jsx
- packages/ui-extender/src/actions/menuAction/menuAction.jsx
- packages/ui-extender/src/actions/menuAction/menuAction.spec.jsx
- Removed shouldComponentUpdate optimization to solve ContentEditor issue ( BACKLOG-14585 )
- Fixed infinite render loop in menu by avoid resetting a state when no value has changed
- Copy target element position for menu item as it gets remove/recreated when shouldComponentUpdate returns true
> BACKLOG-14270 : Menu action fixes

- .npmrc
- README.md
Guild Day Oct. 28, 2020:
* Removes .npmrc to remove the connection between these packages and the Jahia npm registry
* Updates README.md to reflect the process to publish the packages to the public npm registry
> Removes .npmrc and updates README

- packages/ui-extender/src/IframeRenderer/IframeRenderer.container.jsx
https://jira.jahia.org/browse/QA-13109
The waitingMask method is expected to be provided in window by different admin iframe modules. It was provided by gwt in old edit mode, but has never been provided in the new nav.
> QA-13109: Implement a simple waitInProgress method

- packages/data-helper/src/hooks/useTreeEntries/useTreeEntries.gql-queries.js
- packages/data-helper/src/hooks/useTreeEntries/useTreeEntries.js
https://jira.jahia.org/browse/QA-13567
Add-in the sortby functionality to the useTreeEntries hook
> QA-13567: Add-in the sortby functionality to use Tree Entries.

- packages/data-helper/src/fragments/getPermissionFragment.js
- packages/data-helper/src/hooks/useNodeChecks/useNodeChecks.js
- packages/data-helper/src/hooks/useNodeChecks/useNodeChecks.spec.js
- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.gql-queries.js
- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.js
- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.spec.js
https://jira.jahia.org/browse/BACKLOG-15786
Can use `requiredSitePermission` in useNodeChecks :
```
const res = useNodeChecks(
{
...
requiredSitePermission: ['viewContentTab'],
...
}
);
```
> BACKLOG-15786: Check site permissions

- packages/data-helper/src/fragments/fragments.utils.js
- packages/data-helper/src/hooks/useTreeEntries/useTreeEntries.gql-queries.js
- packages/data-helper/src/hooks/useTreeEntries/useTreeEntries.js
https://jira.jahia.org/browse/BACKLOG-19919
The `descendants` without recursionTypesFilter specified will give the same result as children, as it will use by default `{types: 'nt:base', multi: 'NONE'}` (recurse on nothing)
Also replaced lodash usage by standard js
> BACKLOG-19919: Use descendants and recursion filter for useTreeEntries

- packages/data-helper/src/legacy/Picker.tsx
https://jira.jahia.org/browse/BACKLOG-21054
All null checks are now returning undefined after data-helper upgrade, so we have to adjust the checks to falsy values instead.
~~Also openPaths missing on init is now causing issue on cached query and throwing error. Needed to add a default value to fix.~~ Edit: Not needed as this was being set here: https://github.com/Jahia/javascript-components/blob/master/packages/data-helper/src/legacy/Picker.tsx#L165 but was being blocked by the null checks issue which was already fixed.
> BACKLOG-21054: Fix legacy picker for vanity urls

- README.md
- packages/data-helper/package.json
- packages/data-helper/src/fragments/PredefinedFragments.js
- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.gql-queries.js
- packages/data-helper/src/hooks/useNodeInfo/useNodeInfo.js
- packages/scripts/publish.js
https://jira.jahia.org/browse/SEC-104
Remove usage of `SCHEMA_FIELDS_QUERY` and `schemaResult` in `useNodeInfo()` 
From what I can tell, this has been added specifically to check for existence of `existsInLive` GQL field which should now exist since graphql-dxm-provider 2.1 version, and not needed anymore.
> SEC-104: Remove usage of introspection query SCHEMA_FIELDS_QUERY

- packages/design-system-kit/package.json
- packages/design-system-kit/src/actions/DisplayAction.d.ts
- packages/design-system-kit/src/actions/DisplayAction.jsx
- packages/design-system-kit/src/actions/DisplayActions.d.ts
- packages/design-system-kit/src/actions/DisplayActions.jsx
- packages/design-system-kit/src/actions/actionsRegistry.js
- packages/design-system-kit/src/actions/composeActions.js
- packages/design-system-kit/src/actions/index.js
- packages/design-system-kit/src/actions/toIconComponent.jsx
- packages/design-system-kit/src/components/LeftNavigation/LeftDrawerContent/LeftDrawerListItems.jsx
- packages/design-system-kit/src/components/LeftNavigation/LeftMenuItem.jsx
- packages/design-system-kit/src/components/LeftNavigation/LeftNavigation.jsx
https://jira.jahia.org/browse/QA-15281
A check on our code base shown that the updated component: `LeftNavivation` is not used internally. 
Note that the library is marked as deprecate since 2019.
> QA-15281 : copy react-matrials component to design-system-kit package to prevent endless loop in dependencies resolution.

- packages/design-system-kit/package.json
- packages/design-system-kit/src/actions/DisplayAction.jsx
https://jira.jahia.org/browse/QA-15281 
Previous release introduce RXJS dependency that generated an inconsistencies with other bundles. 
this PR to remove it
We had to remove the refresh of the component (action), as the component is deprecated, and not used, this will have no impact.
The DisplayAction from ui-extender has to use instead:
https://github.com/Jahia/javascript-components/blob/master/packages/ui-extender/src/actions/core/DisplayAction.tsx
> QA-15281 : remove RXJS usage from design-system-kit

- packages/scripts/deploy.js
- packages/scripts/pack-project.js
https://jira.jahia.org/browse/BACKLOG-23333
Update the `pack-project.js` script (used by `yarn build`) to pack the content of the `dist/build/` folder into a `dist/<project>-<version>.tgz` file.
If the `dist/build` folder does not exist, fallback to the previous behaviour and pack the root directory directly. This way, we can first release a new version of `@jahia/scripts` that we can then use in https://github.com/Jahia/luxe-jahia-demo, https://github.com/Jahia/npm-create-module, etc.
Similarly, update the `deploy.js` script (used by `yarn deploy` and `yarn watch`) to deploy the `dist/<project>-<version>.tgz` file if `dist/build/` exists. Otherwise, it expects the archive file in the root folder of the project.
> BACKLOG-23333: Pack from dist/build/ and deploy dist/*.tgz

- packages/scripts/deploy.js
https://jira.jahia.org/browse/QA-15406
For the javascript modules, fix the deployment with curl for the `yarn watch` and `yarn deploy` commands.
With a new javascript modules freshly created with `npx @jahia/create-module@latest my-module` (using version _0.0.6_), `yarn watch` and `yarn deploy` commands fail with the following error:
```
Deploying URL curl to Jahia bundles REST API...
node:child_process:965
throw err;
^
Error: Command failed: curl -s --user "root:root1234" --form 'bundle=@.//Users/baptistegrimaud/Documents/code/playground/my-module/dist/my-module-v0.1.0-SNAPSHOT.tgz' --form start=true "http://localhost:8080/modules/api/bundles"
```
The root cause is that the path to the tgz is an absolute path when the curl command expects a relative path.
> QA-15406: Fix curl deployment (yarn watch/deploy)

- packages/scripts/deploy.js
- packages/scripts/pack-project.js
- packages/scripts/pack-utility.js
- packages/scripts/pack.js
Deprecating `jahia-pack` and `jahia-deploy` script provided by _@jahia/scripts_ package as packing should now be performed with `yarn pack` while packing should be done with the `jahia-deploy` script provided by _@jahia/javsscript-modules-library_ package.
> chore: Deprecate pack/deploy scripts
